---
id: Reflection
name: Reflection
full: Method reflection and documentation library
description: |
  The Reflection package provides methods for generationg code reflection and automatic documentation of methods.
  The package has a driver based output generation and currently generates HTML and Text_Wiki output.
list: dev
type: library
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.gnu.org/licenses/lgpl.html
dependencies:
  required:
    php: ^5.3 || ^7
